from sklearn import datasets

In [90]:
!pip install scikit-learn pandas numpy seaborn matplotlib 




In [91]:
breast = datasets.load_breast_cancer()

In [92]:
datasets.load_iris()


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [93]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
data.target[[10, 50, 85]]
list(data.target_names)

[np.str_('malignant'), np.str_('benign')]

In [94]:
breast


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,

In [95]:
 breast.data


array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30))

In [96]:
breast.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [97]:
x,y = datasets.load_iris(return_X_y=True)

In [98]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [99]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [100]:
import pandas as pd

In [101]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

In [102]:
df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [103]:
X = df.drop('selling_price', axis=1)
y = df['selling_price']

In [104]:
X

name  year  km_driven    fuel  \
0                           Maruti 800 AC  2007      70000  Petrol   
1                Maruti Wagon R LXI Minor  2007      50000  Petrol   
2                    Hyundai Verna 1.6 SX  2012     100000  Diesel   
3                  Datsun RediGO T Option  2017      46000  Petrol   
4                   Honda Amaze VX i-DTEC  2014     141000  Diesel   
...                                   ...   ...        ...     ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014      80000  Diesel   
4336           Hyundai i20 Magna 1.4 CRDi  2014      80000  Diesel   
4337                  Maruti 800 AC BSIII  2009      83000  Petrol   
4338     Hyundai Creta 1.6 CRDi SX Option  2016      90000  Diesel   
4339                     Renault KWID RXT  2016      40000  Petrol   

     seller_type transmission         owner  
0     Individual       Manual   First Owner  
1     Individual       Manual   First Owner  
2     Individual       Manual   First Owner  
3     Individual       Manual   First Owner  
4     Individual       Manual  Second Owner  
...          ...          ...           ...  
4335  Individual       Manual  Second Owner  
4336  Individual       Manual  Second Owner  
4337  Individual       Manual  Second Owner  
4338  Individual       Manual   First Owner  
4339  Individual       Manual   First Owner  

[4340 rows x 7 columns]

In [105]:
X.shape

(4340, 7)

In [106]:
y.shape

(4340,)

In [107]:
from sklearn.model_selection import train_test_split

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [109]:
X_train

name  year  km_driven    fuel  \
227                     Mahindra Scorpio S11 BSIV  2017      20000  Diesel   
964                        Maruti Swift Dzire VDI  2018      50000  Diesel   
2045                          Maruti Alto 800 LXI  2013      25000  Petrol   
1025                     Chevrolet Beat Diesel LS  2011      70000  Diesel   
4242              Maruti Vitara Brezza LDi Option  2017      72000  Diesel   
...                                           ...   ...        ...     ...   
3444  Toyota Innova 2.5 G (Diesel) 8 Seater BS IV  2006      50000  Diesel   
466                Tata Indica Vista Quadrajet LX  2011      80000  Diesel   
3092                    Maruti Ciaz VDi Plus SHVS  2016      51000  Diesel   
3772                            Maruti Ertiga VDI  2013      80000  Diesel   
860                   Hyundai Santro Xing GL Plus  2013      80000  Petrol   

     seller_type transmission         owner  
227   Individual       Manual   First Owner  
964   Individual       Manual   First Owner  
2045  Individual       Manual  Second Owner  
1025  Individual       Manual   First Owner  
4242      Dealer       Manual   First Owner  
...          ...          ...           ...  
3444  Individual       Manual   First Owner  
466   Individual       Manual   First Owner  
3092      Dealer       Manual   First Owner  
3772  Individual       Manual   First Owner  
860   Individual       Manual   First Owner  

[3472 rows x 7 columns]

In [110]:
y_train

227     1500000
964      500000
2045      92800
1025      95000
4242     685000
         ...   
3444     500000
466      133000
3092     665000
3772     250999
860      175000
Name: selling_price, Length: 3472, dtype: int64

In [111]:
df = df[['selling_price', 'km_driven', 'year']]

In [112]:
df

selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

Appling Normalization : Minmax Scalling

In [113]:
from sklearn.preprocessing import MinMaxScaler

In [114]:
scaler = MinMaxScaler()

In [115]:
scaled_df = scaler.fit_transform(df)

In [116]:
scaled_df

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]], shape=(4340, 3))

In [117]:
scaled_df = pd.DataFrame(data=scaled_df, columns=df.columns)
scaled_df

selling_price  km_driven      year
0          0.004505   0.086783  0.535714
1          0.012950   0.061988  0.535714
2          0.065315   0.123976  0.714286
3          0.025901   0.057028  0.892857
4          0.048423   0.174807  0.785714
...             ...        ...       ...
4335       0.043919   0.099181  0.785714
4336       0.043919   0.099181  0.785714
4337       0.010135   0.102900  0.607143
4338       0.095158   0.111579  0.857143
4339       0.023086   0.049590  0.857143

[4340 rows x 3 columns]

## Train Test Split

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
X = df.drop('selling_price', axis=1)
y = df['selling_price']

In [120]:
X

km_driven  year
0         70000  2007
1         50000  2007
2        100000  2012
3         46000  2017
4        141000  2014
...         ...   ...
4335      80000  2014
4336      80000  2014
4337      83000  2009
4338      90000  2016
4339      40000  2016

[4340 rows x 2 columns]

In [121]:
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...  
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [122]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [123]:
X_train.shape

(3472, 2)

In [124]:
X_test.shape

(868, 2)

# Feature-Scalling: Normalization : Minmax Scaler

In [125]:
X_train_scalled = scaler.fit_transform(X_train)
X_test_scalled = scaler.transform(X_test)

In [126]:
X_train_scalled

array([[0.02479426, 0.89285714],
       [0.06198751, 0.92857143],
       [0.03099313, 0.75      ],
       ...,
       [0.06322728, 0.85714286],
       [0.09918076, 0.75      ],
       [0.09918076, 0.75      ]], shape=(3472, 2))

In [127]:
X_test_scalled

array([[0.09918076, 0.64285714],
       [0.03347268, 0.96428571],
       [0.05172589, 0.57142857],
       ...,
       [0.04958976, 0.67857143],
       [0.0080325 , 0.89285714],
       [0.03719201, 0.96428571]], shape=(868, 2))

In [128]:
X_train_scalled = pd.DataFrame(data=X_train_scalled, columns = X_train.columns)
X_test_scalled  =pd.DataFrame(data=X_test_scalled, columns = X_train.columns)

In [129]:
X_train_scalled

km_driven      year
0      0.024794  0.892857
1      0.061988  0.928571
2      0.030993  0.750000
3      0.086783  0.678571
4      0.089263  0.892857
...         ...       ...
3467   0.061988  0.500000
3468   0.099181  0.678571
3469   0.063227  0.857143
3470   0.099181  0.750000
3471   0.099181  0.750000

[3472 rows x 2 columns]

In [130]:
X_test_scalled

km_driven      year
0     0.099181  0.642857
1     0.033473  0.964286
2     0.051726  0.571429
3     0.174807  0.785714
4     0.074385  0.857143
..         ...       ...
863   0.074385  0.535714
864   0.148772  0.821429
865   0.049590  0.678571
866   0.008033  0.892857
867   0.037192  0.964286

[868 rows x 2 columns]

In [131]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [132]:
df = pd.read_csv('Social_Network_Ads.csv')

In [133]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [134]:
df.shape    # (rows , columns)

(400, 5)

In [135]:
df.drop('User ID' , axis=1 , inplace=True)

In [136]:
df


Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [137]:
df['Gender'] = df['Gender'].map({'Male':1, 'Female':0})

In [138]:
df

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

# Train Test Split

In [141]:
from sklearn.model_selection import train_test_split

X = df.drop('Purchased', axis=1)
y = df['Purchased']

In [142]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [144]:
X_train

Gender  Age  EstimatedSalary
3         0   27            57000
18        1   46            28000
202       0   39           134000
250       0   44            39000
274       0   57            26000
..      ...  ...              ...
71        0   24            27000
106       0   26            35000
270       0   43           133000
348       1   39            77000
102       0   32            86000

[320 rows x 3 columns]

# Applying StandardScaler

In [145]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [147]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [149]:
X_test

Gender  Age  EstimatedSalary
209       0   46            22000
280       0   59            88000
33        0   28            44000
210       0   48            96000
93        0   29            28000
..      ...  ...              ...
246       0   35            50000
227       1   56           133000
369       0   54            26000
176       0   35            47000
289       0   37            78000

[80 rows x 3 columns]

In [150]:
np.round(X_train.describe(),2)

Gender     Age  EstimatedSalary
count   320.0  320.00           320.00
mean      0.5   37.87         70281.25
std       0.5   10.21         34430.55
min       0.0   18.00         15000.00
25%       0.0   30.00         43000.00
50%       0.5   37.00         71000.00
75%       1.0   45.00         88000.00
max       1.0   60.00        150000.00

In [151]:
np.round(X_train_scaled.describe(),2)

AttributeError: 'numpy.ndarray' object has no attribute 'describe'